baseURL = 'https://nanom.github.io'
languageCode = 'en-us'
title = 'Hern치n J. Maina'

[params]
    description = "My Personal Website"
    keywords = "personal, website, blog, hugo, theme, academic, bootstrap"
    useAvatar = true
    
[params.style]
    bootstrap_css   = "/css/bootstrap.min.css"
    custom_css      = "/css/custom.css"
    bootstrap_js    = "/js/bootstrap.bundle.js"
    custom_js       = "/js/custom.js"
    acl_icon        = "/css/icons/acl.css"
    fontawesome_icon = "/css/icons/fontawesome/css/all.css"
    favicon         = "/images/profile.ico"
    
[params.author]
    name    = "Hern치n J. Maina"
    bio     = "Ph.D. Student in Computer Science. Universidad Nacional de C칩rdoba, Argentina 游뷣릖."
    profile  = "/images/profile.png"
    [params.author.location]
        name  = "C칩rdoba. Argentina"
        icon  = "location-sharp"


[params.social]
    [params.social.email]
        pos = 1
        name = "Email"
        url = "mailto:hernan.maina@mi.unc.edu.ar"
        class = "fa-regular fa-envelope-open"
    
    [params.social.github]
        pos = 2
        name = "Github"
        url = "https://github.com/nanom"
        class = "fa-brands fa-github"
    
    [params.social.acl]
        pos = 4
        name = "Acl Anthology"
        url = "https://aclanthology.org/people/h/hernan-maina/"
        class = "cfa-acl-logo"
    
    [params.social.gscholar]
        pos = 3
        name = "Google Scholar"
        url = "https://scholar.google.com/citations?user=wA3vqywAAAAJ&hl=es"
        class = "fa-solid fa-graduation-cap"